### ISSUE TITLE
After rotating to landscape and back to portrait location UI is broken

### ISSUE THREAD

**Issue by alexsorokoletov** [rolandleth/LTHPasscodeViewController#102]
Even if you rotate on previous page and then open passcode view in a portrait mode.

Was able to reproduce on demo application by enabling landscape orientations in project, then launching the app, rotating it to landscape, rotating back to portrait and pressing button "enable" in the demo app.

**Comment by valdetero** [comment]
@alexsorokoletov is your control open source or available for use?

**Comment by rolandleth** [comment]
Fixed in `3.6.8`.
