### ISSUE TITLE
Passcode Lock shown when opening application from background

### ISSUE THREAD

**Issue by ahanmal** [rolandleth/LTHPasscodeViewController#104]
Even though there is no call for the passcode lock to appear when the application becomes active, it still shows. It looks like https://github.com/rolandleth/LTHPasscodeViewController/blob/19a66fa732d3223fc621e29b33f4da7ad567a6c9/LTHPasscodeViewController/LTHPasscodeViewController.m#L1392-1420 invokes the passcode controller. Is there a way around this?

**Comment by moogle19** [comment]
You are probably sending an ApplicationDidBecomeActiveNotification.
So you have 2 options. Remove the notification in your AppDelegate or remove the observer in the LTHPasscodeViewController: https://github.com/rolandleth/LTHPasscodeViewController/blob/19a66fa732d3223fc621e29b33f4da7ad567a6c9/LTHPasscodeViewController/LTHPasscodeViewController.m#L1560-L1591

**Comment by ahanmal** [comment]
@moogle19 - I'm not sending ApplicationDidBecomeActiveNotification (or I don't think that I am) and it still shows. I just removed the observer in the LTHPasscodeViewController for now. I continue to look into this further.

**Comment by rolandleth** [comment]
I'm not totally sure I understand. The lockscreen appears automatically if there's a passcode set and the timer has ended (if one was provided).

**Comment by ahanmal** [comment]
Yes - the only fix that I found was to remove the observer from LTHPasscodeViewController.

**Comment by rolandleth** [comment]
That's not a bug, that's how the library has always worked. Glad you found a solution 😊
