### ISSUE TITLE
Keyboard getting dismissed

### ISSUE THREAD

**Issue by Oechiih** [rolandleth/LTHPasscodeViewController#106]
Hi,
I think I found a bug but maybe it's just my code.
So imagine this Scenario:
-User opens app
-LTHPasscodeViewController is shown (no TouchID)
-user doesn't enter his passcode but double-presses the homebutton to get to the task switcher*
-then the user isn't switching to another app but just reenters my app again*
-Keyboard is dismissed while the rest of the PasscodeVC is shown
-there's no way for the user to enter except for going to the home screen and tapping the icon again.

*or just opening ControlCenter or NotificationCenter has the same effect

Any help is much appreciated.

**Comment by rolandleth** [comment]
I'm sorry, but issues aren't to be used to ask help. If you're not sure if it's your code or not, please investigate more. I would love to help, but I don't have the required time.
