### ISSUE TITLE
Custom navbar overwritte my current one

### ISSUE THREAD

**Issue by tommy7600** [rolandleth/LTHPasscodeViewController#107]
Hi,
when I add lockscreen with logout button, it overwrites my current nav bar.

**Comment by moogle19** [comment]
I think that is intended, because the lockscreen is displayed over all other screen. It is displayed as a modal view with it's own nav bar.

**Comment by rolandleth** [comment]
It is. The nav bar's purpose is to have where to show the logout button and a title.
