### ISSUE TITLE
Timer lock

### ISSUE THREAD

**Issue by tommy7600** [rolandleth/LTHPasscodeViewController#110]
Hi, 
is it possible to block putting the passcode for some time duration when limit of attempts was reached by user?

**Comment by moogle19** [comment]
I think currently it is not support.
One way you could achieve it is by resigning the FirstResponder of the PasscodeTextField and call becomeFirstResponder with a Timer and the duration you want to disable the passcode lock.

**Comment by tommy7600** [comment]
Ok, thanks for answer :)
