### ISSUE TITLE
Cancel/logout link for entering passcode

### ISSUE THREAD

**Issue by kbadiyani-be** [rolandleth/LTHPasscodeViewController#111]
I Don't see the logout button on the passcode enter/enable screen. Also I believe there is a need for adding cancel link on the enter passcode screen as well just like enable/turnoff screen too.

**Comment by rolandleth** [comment]
Can you reproduce the logout button bug on the demo app? 

Personally I don't see a reason for a cancel button, except maybe, if you want to give reduced functionality without a passcode.
