### ISSUE TITLE
Keeping the lockscreen and modal screens for changing and enabling passcode in portrait mode on Iphone  

### ISSUE THREAD

**Issue by Datadriven** [rolandleth/LTHPasscodeViewController#112]
Hi, 

Great Library, My app supports both landscape and portrait mode on Iphone. But I want to display Lock screen and Modal screens while changing or enabling passcode only in portrait mode and cannot figure how as lock screen rotates to landscape or portrait according to Iphone's orientation change. 
Please help.

**Comment by rolandleth** [comment]
Hey, 


Sadly I can't help, as this isn't an issue related to the control, per se. Try and play with the demo app.
