### ISSUE TITLE
mismatch between header and implementation

### ISSUE THREAD

**Issue by ivdma** [rolandleth/LTHPasscodeViewController#114]
Hey Roland,

I noticed the `passcode` function declaration in header file (instance method `-`) does not match with implementation (class method `+`). Is it a typo or my poor knowledge of Objective-C?

https://github.com/rolandleth/LTHPasscodeViewController/blob/master/LTHPasscodeViewController/LTHPasscodeViewController.h#L74
https://github.com/rolandleth/LTHPasscodeViewController/blob/master/LTHPasscodeViewController/LTHPasscodeViewController.m#L86

**Comment by rolandleth** [comment]
Hey. That's just class a helper that returns the `sharedInstance`'s var: `return [[self sharedUser] _passcode];`

**Comment by ivdma** [comment]
Ah, that explains a lot. But according to README `- (NSString *) passcode` is an instance method (notice instance marker `-`). That is why I got confused. Maybe you need to just fix the README. `LTHPasscodeViewController.passcode` worked for me.

**Comment by rolandleth** [comment]
Hmm, this is weird, because the class method isn't added in the header. But I will update both the header and the README, thanks!
