### ISSUE TITLE
Pod support

### ISSUE THREAD

**Issue by Sean-Wang** [rolandleth/LTHPasscodeViewController#115]
@rolandleth  Do you have plans publish your great framework to pods?

**Comment by rolandleth** [comment]
@Sean-Wang It's already there. The very first line of `How to use` says:

> Drag the contents of LTHPasscodeViewController to your project, or add `pod LTHPasscodeViewController` to your `podspec` file.

**Comment by Sean-Wang** [comment]
I'm sorry. Thanks.
