### ISSUE TITLE
IOS9 iPhone 5 not showing up keyboard

### ISSUE THREAD

**Issue by daymont87** [rolandleth/LTHPasscodeViewController#125]
Hello! You make great passcode. But i found some problems with IOS9:

1) not showing up a keyboard on lockscreen with iPhone 5 (IOS9), so i can't enter pin
2) when you try to close an app from IOS9 multiTask - you can't, because touch id appear every time when you try to close an app

i figure out how to fix second problem, but don't understand what's wrong with keyboard. Can you say how to fix it?

**Comment by daymont87** [comment]
I fixed keyboard bug by adding some delay to viewWillAppear method before call [_passcodeTextField becomeFirstResponder]

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
[_passcodeTextField becomeFirstResponder];
});

**Comment by rolandleth** [comment]
Hey,


I will look at it in the upcoming days, thanks for the help! How did you fix `2)`, though?

**Comment by daymont87** [comment]
Well, it's not actually good solution, i just commented contents of those methods:
- (void)_applicationDidEnterBackground
- (void)_applicationDidBecomeActive
- (void)_applicationWillEnterForeground

and call showLockScreenWithAnimation method manually when i need it(to show lockscreen)

just because IOS9 call applicationDidEnterBackground method when you try to close an app from multitask, so and instead of close an app - touchId window appear. So comment it - was easiest and fastest way for me

**Comment by rin-23** [comment]
Hello,
Problem 1 is still there. Keyboard doesnt show up on launch. Adding the delay seems to fix that.

**Comment by rin-23** [comment]
Hello,

Problem 1 is still there in iOS 9.1. Keyboard doesnt show upon launch. Adding the delay seems to fix the problem though. @daymont87 did you have any problems with that fix?

**Comment by rolandleth** [comment]
I suppose this is related to #130, which was closed due to not being able to be fixed (read more there, please). Can we close this one, too?
