### ISSUE TITLE
Closing passcode view after maxFailedAttempts reached doesn't reset the count

### ISSUE THREAD

**Issue by ddaddy** [rolandleth/LTHPasscodeViewController#126]
We override `maxNumberOfFailedAttemptsReached` after 3 failed attempts. In this method we simply call `[LTHPasscodeViewController close];`
This works great, however if you show the Passcode View again, it still has the message `3 passcode failed attempts` and continues to count upwards from this.

**Comment by rolandleth** [comment]
`_failedAttempts = 0;` is called in `viewDidLoad`, if the passcode is correct in `_validatePasscode`, and in `_dismissMe`. How are you skipping all these steps?

**Comment by rolandleth** [comment]
Can I close this issue?

**Comment by rolandleth** [comment]
I can not reproduce this in the demo project. I tried only calling `[LTHPasscodeViewController close];` in `maxNumberOfFailedAttemptsReached`, but after opening it again, the counter is back to 0.
