### ISSUE TITLE
BugshowForEnablingPasscodeInViewController problem

### ISSUE THREAD

**Issue by lijie250** [rolandleth/LTHPasscodeViewController#128]
My app support Portrait orientations only,

I call the  [[LTHPasscodeViewController sharedUser] showForEnablingPasscodeInViewController:self asModal:YES];

but crash,hardware is iPhone5 and iOS9.0:
Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [LTHPasscodeViewController shouldAutorotate] is returning YES'

**Comment by rolandleth** [comment]
Can you reproduce it in the demo app?

**Comment by lijie250** [comment]
Yes,it crashed if you call the [[LTHPasscodeViewController sharedUser] showForEnablingPasscodeInViewController:self asModal:YES]

You need the demo project?

**Comment by rolandleth** [comment]
I meant if you can reproduce it in the demo app provided in the repo. If yes, where are you calling that line from?

**Comment by rolandleth** [comment]
Fixed in `3.6.8`.
