### ISSUE TITLE
v3.6.7 crashes due to wrong return value of `supportedInterfaceOrientations` method

### ISSUE THREAD

**Issue by allenhsu** [rolandleth/LTHPasscodeViewController#129]
**Crash:**
```
Fatal Exception: UIApplicationInvalidInterfaceOrientation
Supported orientations has no common orientation with the application, and [LTHPasscodeViewController shouldAutorotate] is returning YES
```

**Related method:**
```
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
	if (_displayedAsLockScreen)
        return LTHiOS8 ? UIInterfaceOrientationMaskPortrait : UIInterfaceOrientationMaskAll;
	// I'll be honest and mention I have no idea why this line of code below works.
	// Without it, if you present the passcode view as lockscreen (directly on the window)
	// and then inside of a modal, the orientation will be wrong.
	
	// If you could explain why, I'd be more than grateful :)
	return UIInterfaceOrientationMaskPortraitUpsideDown;
}
```

In versions before v3.6.7, you mistakenly used `UIInterfaceOrientationPortraitUpsideDown` (2), which should be `UIInterfaceOrientationMaskPortrait` (2), coincidentally they have same value of 2, so it worked.
In v3.6.7, you used `UIInterfaceOrientationMaskPortraitUpsideDown` of which the value is actually (1 << 2 = 4), so the app crashes.

**Solution:**
You should use `UIInterfaceOrientationMaskPortrait`.

**Comment by rolandleth** [comment]
I need to test if everything else keeps working, since, as I wrote there, I don't know why it worked before only like that. Thanks for the tip!

**Comment by ddaddy** [comment]
I can confirm this too. Using `UIInterfaceOrientationMaskPortrait` works and stops the crash.

**Comment by rolandleth** [comment]
Fixed in `3.6.8`, would be great if any of you could confirm and close.

**Comment by ddaddy** [comment]
I already made the change in my code and it worked :)
While your here, could you take a look at https://github.com/rolandleth/LTHPasscodeViewController/issues/126

**Comment by rolandleth** [comment]
Hopefully I will manage to, later during the day. What about this issue, #129? :)
