### ISSUE TITLE
application:didFinishLaunchingWithOptions: loop

### ISSUE THREAD

**Issue by zentraedi** [rolandleth/LTHPasscodeViewController#130]
Hi fellows!

I'm using your excellent library in one of the apps i'm working on and i've come across a weird problem when using LTHPasscodeViewController to secure the access.

I show the lock screen at application:didFinishLaunchingWithOptions: so the user encounters the lock screen on application launch. Subsequently i call the method to lock the screen in applicationWillEnterForeground for when the user puts the app in background, switches between app, etc...

Everything works fine except for when i'm in the app, locked or not, then i double tap the home button to bring the app switcher and try to close the app. I slide the app up to terminate, the app terminates but immediately the prompt for the user's fingerprint appears again preventing the app from closing.

I can close the app only by switching to another app then bring the app switcher and terminate the app.

Any ideas?

Thanks in advance.

**Comment by rolandleth** [comment]
Hey,

So `applicationWillEnterForeground` gets called when terminating the app from the app switcher?

**Comment by zentraedi** [comment]
Actually no. This is the order the application delegate is being called:

-[AppDelegate applicationDidEnterBackground:]
-[AppDelegate applicationWillTerminate:]

**Comment by rolandleth** [comment]
I can't really understand why the TouchID alert is being presented. What if you cancel? The app doesn't get terminated?

**Comment by zentraedi** [comment]
If i cancel then it shows the PIN based lockscreen and asks the user to enter the PIN.

You can see the behavior i'm describing here:

https://www.dropbox.com/s/xboyfxhcf2fewbf/ec_loop.mov?dl=0

**Comment by rolandleth** [comment]
That's weird. Thanks for the video, I'll try to look at it when I have some time.

**Comment by zentraedi** [comment]
If i only call LTHPasscodeViewController in applicationDidBecomeActive the the app enters in a infinite loop: unlocks, locks, unlocks, locks... and can't do anything else.

Here's what i've found recently:

If a don't call LTHPasscodeViewController in application:didFinishLaunchingWithOptions: and close the app from the app switcher, it closes as expected. Note that no call to the lockscreen was made, LTHPasscodeViewController didn't show once.

If i press the home button or switch to another app and then come back i get the lock screen. I unlock normally and get to the app's homescreen, now if i want to close the app from the app switcher then it enters the loop described previously.

It appears that it happens after LTHPasscodeViewController shows for the first time, if it's not shown then there's no problem at all.

Thanks.

**Comment by rolandleth** [comment]
I'm sorry, but I have no real time to investigate this in the near future :(

**Comment by rolandleth** [comment]
The problem is that when killing the app, `_applicationDidEnterBackground` is called and, in turn, `showLockScreenWithAnimation` is called (as it should), but `_isCurrentlyOnScreen` can't really be set to `true` anywhere at this point, so it doesn't call `showLockScreenWithAnimation`.

I will look more into solutions.

**Comment by zentraedi** [comment]
I ended up commenting the line that shows the lock screen in ```_applicationDidEnterBackground```

For some reason, the the app didn't show the lockscreen when going to background, all this time i've been doing that manually since it didn't work automatically.

**Comment by rolandleth** [comment]
Glad to hear. Can we close the issue, then?

**Comment by zentraedi** [comment]
Yeah, sorry it took so long. Just thought should let everyone know.

Thanks.
