### ISSUE TITLE
logout button will disappear when using touch ID

### ISSUE THREAD

**Issue by braincover** [rolandleth/LTHPasscodeViewController#131]
Logout button and navBar will be removed when I cancel the touch ID alert ( by _resetUI ), then I will trapped in passcode view if I haven't handle maxNumberOfFailedAttemptsReached.

**Comment by rolandleth** [comment]
I will look into it, but `maxNumberOfFailedAttemptsReached` shouldn't be left unhandled, in my opinion.

**Comment by rolandleth** [comment]
Can you check the latest build, please? `3.7.4`.

**Comment by rolandleth** [comment]
@braincover Can I close the issue?

**Comment by rolandleth** [comment]
Since I can't reproduce the issue and there has been no reply in the past week, I'm going to close the issue.
