### ISSUE TITLE
calling with IBAction

### ISSUE THREAD

**Issue by TacoAsian** [rolandleth/LTHPasscodeViewController#132]
I am sorry I am new to program and don't know where to get help
I installed it with pod and it went great but as I called it with IBAction with perform segue after it, the lockscreen didnt show up and it perform the segue without the lockscreen,
Sorry for my bad english and here's my code
-(IBAction)enterPin: (UIButton*)sender{
[LTHPasscodeViewController useKeychain:NO];
if ([LTHPasscodeViewController doesPasscodeExist]) {
    if ([LTHPasscodeViewController didPasscodeTimerEnd])
        [[LTHPasscodeViewController sharedUser] showLockScreenWithAnimation:YES
                                                                 withLogout:NO
                                                             andLogoutTitle:nil];
}
[self performSegueWithIdentifier:@"pinLogin" sender:nil];
}

**Comment by rolandleth** [comment]
I'm sorry, but I haven't really worked with IB, so `LTHPasscodeViewController` doesn't really support it.

**Comment by rolandleth** [comment]
I will close this now, sorry. Maybe I will add more support to IB in the future, but I wouldn't get my hopes too high about it.
