### ISSUE TITLE
What if I need to compare entered passcode to the passcode stored in external web application?

### ISSUE THREAD

**Issue by velikanov** [rolandleth/LTHPasscodeViewController#135]
eg for SMS verification code functionality

maybe we can do some "didFinishEnteringPasscode"?

or can we give the functionality to write custom validator instead of _validatePasscode if implemented?

**Comment by rolandleth** [comment]
I don't really understand what you need. You can already save the passcode somewhere else than the keychain, by calling `[LTHPasscodeViewController useKeychain:NO]`. Then the validation is done by comparing the entered passcode with the one on your web app (fetching the passcode has to be done by you, via a protocol method).

**Comment by velikanov** [comment]
@rolandleth, yeah, you are perfectly right, Roland
but fetching the plain passcode is a potential vulnerability, isn't it? I don't think that passing the passcode to verification consumer is a good idea…

what if I can switch the default _validatePasscode routine to custom one in which I can send entered passcode to the web service that will check the entered passcode.

what do you think? is it a good use-case?

**Comment by rolandleth** [comment]
You could fetch it encrypted and decrypt it before returning it?

**Comment by velikanov** [comment]
yes, you are right as always
the most annoying thing here that I need to keep the passcode encoding strategy (md5/sha512 etc., salts and so on) synced between web application and iOS application…
closing this, thank you!

**Comment by rolandleth** [comment]
Glad we found a way out :)
