### ISSUE TITLE
Alignment changes in UI

### ISSUE THREAD

**Issue by safecase123** [rolandleth/LTHPasscodeViewController#136]
Thanks for great library. I would like to report one issue

![passcode](https://cloud.githubusercontent.com/assets/1125736/12143588/cf1bb0f6-b44f-11e5-94af-9237e98021cd.png)

**Comment by rolandleth** [comment]
Hey, thanks for reporting. What device, iOS and simulator or real device?

**Comment by safecase123** [comment]
its simulator that i am using

**Comment by rolandleth** [comment]
What iOS version, any steps to reproduce? Anything else than "this is the problem" helps.

**Comment by rolandleth** [comment]
I'm sorry, but I can not reproduce this on the demo project.
