### ISSUE TITLE
Entering passcode is not possible when changing allowUnlockWithTouchID to NO

### ISSUE THREAD

**Issue by relatedcode** [rolandleth/LTHPasscodeViewController#138]

**Comment by relatedcode** [comment]
@rolandleth To be precise it works fine if I exit the app and open it again. But when I change allowUnlockWithTouchID to NO and the app only goes to background (not terminated) and open it again I only get a blank screen. Entering the passcode in this situation is not possible for me. Any idea? Did I miss something? Thanks!

**Comment by relatedcode** [comment]
@rolandleth Anyway, awesome job! :)

**Comment by rolandleth** [comment]
Thanks :)

I will try to have a look today or tomorrow.

**Comment by relatedcode** [comment]
@rolandleth Ok, thanks! Please let me know if you need any further information related to this issue.

**Comment by rolandleth** [comment]
@relatedcode Could you check the latest version, please? A PR was merged that allows for optional `allowUnlockWithTouchID`, and I can not reproduce the behavior you described on the Demo project.

**Comment by relatedcode** [comment]
@rolandleth Ok. Will be checked. Thanks!

**Comment by relatedcode** [comment]
This seems absolutely ok for me now. Thanks!

However we have an other similar situation. New issue will be opened for that.
