### ISSUE TITLE
Entering passcode is not possible when turning Passcode off in Settings

### ISSUE THREAD

**Issue by relatedcode** [rolandleth/LTHPasscodeViewController#140]

**Comment by relatedcode** [comment]
@rolandleth 

When

1., the iOS Passcode is on,
2., one or more fingerprint is added,
3., the app is in the background,
4., the allowUnlockWithTouchID is set to YES,

and I turn OFF the Passcode in iOS Settings, then I cannot enter the Passcode in the app. I only get a blank screen.

If I exit the app and start it over, the Passcode can be entered.

Thanks!

**Comment by rolandleth** [comment]
@relatedcode, could you check the latest build, please?

**Comment by relatedcode** [comment]
Ok. Checking...

**Comment by relatedcode** [comment]
@rolandleth The updated code seems absolutely fine for me now. Thanks! :)

**Comment by rolandleth** [comment]
Thank you too!
