### ISSUE TITLE
Support for popover for iPADs

### ISSUE THREAD

**Issue by Ankish** [rolandleth/LTHPasscodeViewController#141]
Currently it does not support for popovers . It would be great to have this feature. The default UI for security in iPAD is with popover. Let me know if its possible @rolandleth .

Thank you for the rocking library :+1:

**Comment by rolandleth** [comment]
Hey,

Sadly I don't have that much time to add new features, but if you or someone else is willing to open a PR with such a feature, I'd be more than glad to merge it.
