### ISSUE TITLE
Breaks When Displaying Modal While Still On Screen

### ISSUE THREAD

**Issue by johnnyshankman** [rolandleth/LTHPasscodeViewController#143]
My application sometimes has to open a modal on the view being currently covered by the LTHPasscodeViewController.

This causes the keyboard to disappear, but more importantly causes the view to be incapable of showing it once again via calls to `becomeFirstResponder`.

I made sure the call is being called in the main thread and even tried delaying the call but nothing. 

User's stuck without being able to type in the pword.

I think the multi-window situation gets messed up when a modal is presented from the other view while LTHPasscodeVC is still on screen, causing the LTHPasscodeVC to get lost in the view hierarchy or something. I remember reading keyboards can't show on detached windows, probably has something to do with this issue.

**Comment by johnnyshankman** [comment]
Calls for `becomeFirstResponder` return true and the view claims the textfield `canBecomeFirstResponder` is also true.

**Comment by johnnyshankman** [comment]
I think it might be getting swapped in the hierarchy and ending up in front of the keyboard?

**Comment by johnnyshankman** [comment]
Yep that is indeed what is happening. Any idea how to fix it?

I get confirmation from the app delegate that the keyboard displayed, meaning it is on screen it's just suddenly behind the LTH view..

**Comment by johnnyshankman** [comment]
```
    [self.view endEditing:YES];
    [self.passcodeTextField setUserInteractionEnabled:NO];
    [self.passcodeTextField setUserInteractionEnabled:YES];
    [self.passcodeTextField becomeFirstResponder];
```

this as a callback for touching works on sim but not on any actual devices. Can we please add a tap gesture recognizer that brings up the keyboard?

**Comment by johnnyshankman** [comment]
Issue resolved trivially but I can't fix the actual problem.

Here's my hack for anyone having trouble showing the keyboard once an external Modal Presentation causes it to disappear.
```
    // Wherever you want to do this
    [_animatingView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(showkeyboard)]];
```
```
-(void)showkeyboard {
    [self _cancelAndDismissMe];
    [self showLockscreenWithoutAnimation];
}
```

**Comment by rolandleth** [comment]
Hey,

The gesture recognizer idea is rather nice, I will think about other ways, and use this one, if I can't manage to find a proper fix.

**Comment by johnnyshankman** [comment]
@rolandleth 

Reproduction steps:

1. Show the LTHPasscodeViewController
2. While still displaying the LTHPVC, modally present another view controller.
3. The keyboard will hide due to the LTHPVC losing fireresponder status
4. Because the view is now floating in its own window, it cannot regain the keyboard with `[_passcodeField becomeFirstResponder]`

**Comment by rolandleth** [comment]
Hey @johnnyshankman ,

The problem is that the lockscreen is - and should be, in my opinion, added on the window, so it can cover everything else, especially in the multitasking view, and presenting a modal will add it below the lockscreen. I think the only solution is yours, to manually dismiss and show the lockscreen after the modal was presented.
