### ISSUE TITLE
Doesn't Work With ARC, Lots of Leaks

### ISSUE THREAD

**Issue by johnnyshankman** [rolandleth/LTHPasscodeViewController#144]
Highly suggest replacing `LTHPasscodeUtils` with `SSKeychain`

https://github.com/soffes/sskeychain

Will be forking and making a PR for this. It's working leakless in my application currently.

All you have to do is import that library, add your `Security.framework`, and then replace all the calls to set and and get password with the equivalent calls from the SSKeychain library. Very simple.

**Comment by rolandleth** [comment]
Hey,

At some point I thought of replacing it, but since no one complained about any issues, I thought it's better to go with what's already there, but if you say there are problems and are willing to open a PR, I will gladly look over it and merge it.

Thanks!

**Comment by johnnyshankman** [comment]
@rolandleth I'll definitely try to get that done sometime soon. SSKeychain works great!

**Comment by rolandleth** [comment]
@johnnyshankman I was looking through the Leaks instrument, and it doesn't appear to catch any leaks. Could you help out on how to find them? Maybe they can be easily fixed.

**Comment by rolandleth** [comment]
Fixed in `3.7.9`.
