### ISSUE TITLE
Can you make the library a bit more intuitive to use?

### ISSUE THREAD

**Issue by Sweeper777** [rolandleth/LTHPasscodeViewController#147]
I put the equivalent swift code of the objc code in the example in README.md into `didFinishLaunchingWithOptions` and ran the app. Nothing happened at all. Then I try to read the code in the demo project.

After a long time (I can't read objc code very well), I finally figured out that I should call `showForEnablingPasscodeInViewController`. Now I am really confused about what those code in `didFinishLaunchingWithOptions` are doing.

Also, I don't really understand why the correct passcode is stored in the delegate. Can't I pass the passcode as a method parameter?

Therefore, I feel like this is kind of counter-intuitive. I would want to do something like this: (in Swift)

```
let passcodeVC = LTHPasscodeViewController()
passcodeVC.correctPasscode = "blah"
passcodeVC.isSimple = true
passcodeVC.modalPresentationStyle = .FormSheet
passcodeVC.touchIDEnabled = false
passcodeVC.delegate = self
// ...
self.presentViewController(passcodeVC, animated: true, completion: nil)
```

And the delegate should only contain stuff like `didEnterWrongPasscode`, `didEnterCorrectPasscode`, `passcodeVCDidCancel` etc.

Isn't that much more intuitive? Or did I misunderstood your objective c code?

**Comment by rolandleth** [comment]
Hey,

Maybe nothing happened because you didn't have a passcode yet. 
Which `didFinishLaunchingWithOptions`? Inside the library?
What do you mean the passcode is stored in the delegate? It's saved in the Keychain, and retrieved from there, as well.You do have the option to save the passcode yourself, somewhere else, that's what all those protocol methods are for: saving all the critical stuff in a custom location.

**Comment by Sweeper777** [comment]
How can I 'have a passcode'? I set my passcode in the 'Passcode' section of the settings app, don't I?  If you meant _that_ passcode, I do have one! If that's not what you meant, how can I have one? I can't really read objective c code that well. And the `didFinishLaunchingWithOptions` is in my AppDelegate.swift file. I know that the passcodes are saved in the Keychain. But my ultimate goal in the first place is to store multiple passcodes, not necessarily in custom locations.

Furthermore, I need to separate the UI code from the code that you are trying to demonstrate, which is very hard for me. I am really confused. Can you please just put code snippets in the README file to show people how to present the controller properly?

**Comment by rolandleth** [comment]
No, I mean a passcode in the app, not your phone. Run the demo project and you'll see an "Enable" button there. 

If you need multiple passcodes in the same app, then this library won't be of use: it's a singleton, meaning it will handle one passcode per app.

The snippets required to present the controller properly *are* in the README: that's all you need to do, to present the lockscreen view, but a passcode must be first created; which is also in the README:

```objc
- (void)showForEnablingPasscodeInViewController:(UIViewController *)viewController asModal:(BOOL)isModal;
```

Then, if you have this in your `didFinishLaunchingWithOptions`, the lockscreen view will be displayed:

```objc
[LTHPasscodeViewController useKeychain:NO];
if ([LTHPasscodeViewController doesPasscodeExist]) {
    if ([LTHPasscodeViewController didPasscodeTimerEnd])
        [[LTHPasscodeViewController sharedUser] showLockScreenWithAnimation:YES
                                                                 withLogout:NO
                                                             andLogoutTitle:nil];
}
```

Or you can do it manually, example also found in the README:

```objc
- (void)showLockScreenWithAnimation:(BOOL)animated withLogout:(BOOL)hasLogout andLogoutTitle:(NSString*)logoutTitle;

// Example:
[[LTHPasscodeViewController sharedUser] showLockscreenWithAnimation:YES withLogout:NO andLogoutTitle:nil];
```

**Comment by Sweeper777** [comment]
Oh I see now! Apparently, I can't read Objective-C code. Thanks for pointing that out!
