### ISSUE TITLE
Where do you get the translation of the nav bar title from? Can you change it?

### ISSUE THREAD

**Issue by Sweeper777** [rolandleth/LTHPasscodeViewController#149]
I see that the text in the navigation bar changes with the iPhone language. For example, the disable passcode screen in simplified Chinese:

<img width="316" alt="screen shot 2016-07-13 at 8 48 32 am" src="https://cloud.githubusercontent.com/assets/13585047/16788347/d624d1e0-48d6-11e6-9e0b-6734c560b42a.png">

In simplified Chinese, the translations are alright. But in traditional Chinese, I, as a native speaker, think that the translation is kind of weird.

The traditional Chinese translation for "Disable Passcode" in the passcode view controller is "關閉密碼", which means "Close Passcode". The verb "關" means "to close", as in "關門(to close a door)". You can also use "關" to mean " to turn off" if it is used with electrical appliances, as in "關燈 (to turn off a light)".

Therefore, you can't really "關" passcode since it is neither an electrical appliance nor something that can be "closed".

People _can_ understand it though, but not immediately.

So I just want to ask where do you get those translations from. If you get them from the OS, then obviously you can't change it. But if you get it from somewhere else, then can you change it to "停用密碼 (stop using passcode)"?

**Comment by rolandleth** [comment]
Hello,


Thanks for the explanation! But translations were done by users, via pull requests, so if you could open one, I'd be happy to merge it.

**Comment by Sweeper777** [comment]
Can you tell me which file to edit? Because I can't read Objective-C code that well. Is it a .strings file?

**Comment by Sweeper777** [comment]
Nevermind, I found it. I'm kind of busy today, so I'll do it tomorrow

**Comment by Sweeper777** [comment]
Hey, I just created a pull request. Please consider merging it.

**Comment by rolandleth** [comment]
Done, merged #150, thanks!
