### ISSUE TITLE
I can't "swipe the app out" when TouchID is enabled!

### ISSUE THREAD

**Issue by Sweeper777** [rolandleth/LTHPasscodeViewController#151]
I don't know what that screen in which you can swipe an app up to kill the process is called...

So I double press Home button and this screen appears right?

![simulator screen shot jul 19 2016 4 23 51 pm](https://cloud.githubusercontent.com/assets/13585047/16943270/777d73d0-4dcd-11e6-9fb5-24df3509950a.png)

Notice the app "EZDiary". That is the app using `LTHPasscodeViewController`. Now I swipe the app up to kill the process:

![simulator screen shot jul 19 2016 4 26 48 pm](https://cloud.githubusercontent.com/assets/13585047/16943320/b206ccfe-4dcd-11e6-8bcb-aaa4c5926c74.png)

if the device doesn't have a TouchID, it kills the process just fine. However, if TouchID is enabled, just after I swiped the app up, the app opens again and ask me for the TouchID! Because of this, I can't kill the process! It's like an infinite loop!

I basically put this code in `viewDidLoad` of the initial view controller:

        if LTHPasscodeViewController.doesPasscodeExist() {
            LTHPasscodeViewController.sharedUser().showLockScreenWithAnimation(true, withLogout: true, andLogoutTitle: nil)
        }

Why did this happen? `viewDidLoad` certainly doesn't get called when I swipe the app up, right?

Yeah I know I didn't put the code in the app delegate. But it doesn't seem to work if I put it there. The passcode view controller just doesn't show up. It only works if I put it in `viewDidLoad`.

**Comment by Sweeper777** [comment]
By the way, can you add my app to the list of apps that uses this at the bottom of README? Here's the link: https://itunes.apple.com/us/app/ezdiary-my-diary/id1128083826?ls=1&mt=8

**Comment by jnavarrom** [comment]
Hi

In the file _LTHPasscodeViewController.m_ comment the lines 1458, 1459, 1460 and try again

```
[self showLockScreenWithAnimation:NO
                       withLogout:NO
                 andLogoutTitle:nil];
```

**Comment by rolandleth** [comment]
Hey,

This is a known issue (sadly, I can't find the previous one to link it), it's due to the system calling `didBecomeActive` / `willEnterForeground` when killing the app. Why? No idea.

If you do remove those lines, then the app won't be protected while in the background, so you might end up disclosing sensitive information while on the multitasking view.

I haven't managed to find a way around this, due to the weird system call mentioned above. It appears to work fine on iOS 9, and, sadly, I can not test on iOS 8 anymore.

**Comment by jnavarrom** [comment]
If the passcode is enable, you can add a subview to the appdelegate's _window_ when the apps enters in background (if the passcode is enabled), this way you won't disclose any information.

**Comment by Sweeper777** [comment]
@jnavarrom That sounds like a great idea! Since I can't write Objective-C, can you create a PR?

@rolandleth So that view is called "multitasking view"? I never heard of it until now. Also, it _doesn't_ work on iOS 9! My phone is running iOS 9 and it always asks me for TouchID!

**Comment by rolandleth** [comment]
There is already logic for exactly that, `1462-1466`, but only if there is a timer on the lockscreen. If there is no timer, or it has ended, the lockscreen is presented on `enterBackground`; I suppose it could always use the `coverView` on `enterBackground`, and show the lockscreen on `enterForeground`.

The multitasking view is when you double-press the home button.

**Comment by rolandleth** [comment]
You can even delete `1450-1462` and `1466`, then you'll still have a cover on the multitasking view. Requires a bit of testing, though, as I haven't - I just tested it a couple of times.

**Comment by Sweeper777** [comment]
I tried it on an iPhone 6s Plus running iOS 9.3.2. When I opened the app, it looks like this:

![screen shot 2016-07-19 at 8 27 58 pm](https://cloud.githubusercontent.com/assets/13585047/16949843/81dcea78-4def-11e6-9c6a-737b84a4e5e3.png)

Then I tapped "Cancel" this appears:

![screen shot 2016-07-19 at 8 28 20 pm](https://cloud.githubusercontent.com/assets/13585047/16949852/9757ca3a-4def-11e6-96e1-2cd2f77a4b76.png)

As you can see, it's all kind of messed up!

Any ideass?

**Comment by Sweeper777** [comment]
Never mind. I put the code in the wrong place...
