### ISSUE TITLE
disablePasscodeWhenApplicationEntersBackground does not work correctly.

### ISSUE THREAD

**Issue by tranngoclinh88** [rolandleth/LTHPasscodeViewController#152]
I had call disablePasscodeWhenApplicationEntersBackground() when display passcode view controller but in viewWillAppear() method _addObsers() is called and re-added observers again.
So disablePasscodeWhenApplicationEntersBackground() does not work correctly.

**Comment by rolandleth** [comment]
Hey,

Can you reproduce this on the demo app?

**Comment by rolandleth** [comment]
It has been almost a month now, I will consider this as no longer valid.
