### ISSUE TITLE
Callback after enabling passcode?

### ISSUE THREAD

**Issue by skrosoft** [rolandleth/LTHPasscodeViewController#156]
Hi,

Is there a way to call a function where passcode has been enabled?

`LTHPasscodeViewController.sharedUser().showForEnablingPasscode(in: self, asModal: true);`

Thanks!

**Comment by rolandleth** [comment]
Hey, 

Sadly, that's one of the few cases where a callback doesn't happen, but when enabling the postcode successfully, the controller closes, and you get a callback for that, `passcodeViewControllerWillClose`.

**Comment by skrosoft** [comment]
Okay, thank you for your confirmation. You should mark this issue with the label "enhancement ".

Have a nice day.

**Comment by rolandleth** [comment]
Added in `3.7.10`, 958b32265d6f450fc11f884fb839079721363ca8.
