### ISSUE TITLE
Variable digits count

### ISSUE THREAD

**Issue by brandFromNSK** [rolandleth/LTHPasscodeViewController#157]
Hi,

Can you add a chance to set variable count of digits in future?

Thanks!

**Comment by rolandleth** [comment]
Hey,


There was another request like this, but I can't find it. I was waiting on a pull request for it, and I forgot about it, but I will try to implement it today.

**Comment by brandFromNSK** [comment]
Thanks for fast answer!

**Comment by DimaSlk** [comment]
I've just created pull request with needed changes.

**Comment by rolandleth** [comment]
Added in [3.8.0](https://github.com/rolandleth/LTHPasscodeViewController/releases/tag/3.8.0).
