### ISSUE TITLE
Can the library adds enablePasscodeWhenApplicationEntersBackground

### ISSUE THREAD

**Issue by konnanl** [rolandleth/LTHPasscodeViewController#158]
I can see that disablePasscodeWhenApplicationEntersBackground is removed the observer from the library. Can the library also adds the enablePasscodeWhenApplicationEntersBackground to re-enable the function?

**Comment by rolandleth** [comment]
Will be added in `3.7.10`.

**Comment by rolandleth** [comment]
Added in `3.7.10`, 958b32265d6f450fc11f884fb839079721363ca8
