### ISSUE TITLE
Back button in ChangePasscodeView doesn't call _cancelAndDismissMe method

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#160]
In demo application, you should do next

- in class LTHDemoViewController.m change method showLockViewForChangingPasscode to

`- (void)showLockViewForChangingPasscode {
    [LTHPasscodeViewController sharedUser].hidesCancelButton = NO;
    [LTHPasscodeViewController sharedUser].hidesBackButton = NO;
	[[LTHPasscodeViewController sharedUser] showForChangingPasscodeInViewController:self asModal:NO];
}`

- run application
- enable passcode
- press **Change** button
- enter old passcode
- press **Back** button
- press **Change** button again

You see "Enter your new passcode" instead of "Enter your old passcode". If instead of **Back** button you press **Cancel** everything works OK.

As I understand, by pressing **Cancel** button you call `_cancelAndDismissMe` method but doesn't do the same by pressing **Back** button.

**Comment by rolandleth** [comment]
Fixed in `3.7.9`

**Comment by rolandleth** [comment]
Hey,


Thanks! It's now fixed and to be released shortly.


Roland
