### ISSUE TITLE
passcodeWasEnteredSuccessfully called twice

### ISSUE THREAD

**Issue by skrosoft** [rolandleth/LTHPasscodeViewController#161]
Hello,

It seems that the function passcodeWasEnteredSuccessfully is called twice after calling showForEnablingPasscode. 

Vincent

**Comment by rolandleth** [comment]
Hello,


Do you know if this was introduced in the last build? Can you give more details on how to reproduce it, please? Does it happen in the demo app too?


Thanks.

**Comment by rolandleth** [comment]
When enabling, it doesn't even appear once in the demo app for me 🤔

**Comment by skrosoft** [comment]
I'm using the latest version 3.7.9 from cocoapods. I still don't know why this happen.
In the demo app, it works fine.

**Comment by rolandleth** [comment]
Could you try to reproduce it in the demo app?

**Comment by skrosoft** [comment]
Sorry for the late answer, I can now confirm that this problem was mine
