### ISSUE TITLE
Keyboard not coming up?

### ISSUE THREAD

**Issue by SunnyShah407** [rolandleth/LTHPasscodeViewController#162]
When you first time open LTHPasscodeViewController it open keyboard. now when you press home button and come back keyboard not coming up.

**Comment by rolandleth** [comment]
Can you reproduce it in the demo app? For me it's working, you just need to _Toggle Soft Keyboard `(command K)`_

**Comment by SunnyShah407** [comment]
I am using device not simulator. its simple just press home button and come back

**Comment by rolandleth** [comment]
OK, but can you reproduce it on the demo app? Because for me it's working.

**Comment by SunnyShah407** [comment]
Its my mistake. I am presenting viewcontroller every time. fixed using 

  if (self.isCurrentlyOnScreen) {
        return;
    }

On - (void)showLockScreenWithAnimation:(BOOL)animated withLogout:(BOOL)hasLogout andLogoutTitle:(NSString*)logoutTitle; method

**Comment by rolandleth** [comment]
But that method already has that check, internally 😕

Can I close the issue?
