### ISSUE TITLE
No content on Change PIN screen after unlock application with Touch ID

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#163]
1. Open demo application. TouchID should be ON;
2. Press Change button;
3. Press Back (< Demo) button;
4. Press Home button and then open application again;
5. Unlock with TouchID;
6. Press Change button

Text and dashes for PIN code absent on screen.

**Comment by rolandleth** [comment]
Oh, wow, this bug goes back for so long. Thanks, will look into it today!

**Comment by rolandleth** [comment]
Added in [3.8.0](https://github.com/rolandleth/LTHPasscodeViewController/releases/tag/3.8.0).
