### ISSUE TITLE
Window Title problem

### ISSUE THREAD

**Issue by skrosoft** [rolandleth/LTHPasscodeViewController#165]
Hello @rolandleth 

There is a bug with the title.

If i call `showForChangingPasscode`, the title is ok ("Change Password").

After that, if I call `showLockScreen` with `withLogout=true` the title is still "Change password".

It should be blank again.

For the moment, I solved it by calling:

`LTHPasscodeViewController.sharedUser().title = "";`

Vincent

**Comment by rolandleth** [comment]
Hey, 


Thanks, I'll look into it today.

**Comment by rolandleth** [comment]
Fixed in 16e9474b, will be released in next version. Thanks again!
