### ISSUE TITLE
Property 'viewLoaded' not found on object of type 'LTHPasscodeViewController *';

### ISSUE THREAD

**Issue by daushn** [rolandleth/LTHPasscodeViewController#168]
In "setDigitsCount" method Xcode warns about this error: 

Property 'viewLoaded' not found on object of type 'LTHPasscodeViewController *'; did you mean 'viewIfLoaded'?

**Comment by rolandleth** [comment]
No, `viewLoaded`, but its getter is `isViewLoaded`. My mistake, but for me it works without errors or warnings. Does it work properly, though?

Will fix in next version, anyway.

**Comment by rolandleth** [comment]
Fixed in `3.8.2`, e23049b2.
