### ISSUE TITLE
Can't enable Touch ID after 5th unsuccessful try (iOS 10+)

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#169]
This issue reproduces only with iOS 10+

1. Run demo app
2. Enable Touch ID if it wasn't
3. Press the Test button
4. Enter **three** times wrong finger
5. Enter correct PIN
6. Press the Test button again and enter **two** more wrong fingers
7. Enter correct PIN

After it, Touch ID switch is turned off. And there is no way to turn it on. If you turn it on and then press Test button you won't see Touch ID pop-up. If you force stop application and then run it again Touch ID switch component will be hidden.

On iOS 9 after 5th unsuccessful tries, you see system screen which requires you to enter iPhone passcode and then Touch ID works correctly again.

**Comment by rolandleth** [comment]
Sadly I'm running 10.2 on my phone, without an Xcode beta, but I will try to find time to look into it.

**Comment by rolandleth** [comment]
This is a system restriction: it will lock you out of TouchID until you lock your phone and unlock it again. I've tried 1Password, and it happens the same.
