### ISSUE TITLE
Deny ability to reuse old PIN code during PIN changing

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#170]
If you open phone _Settings > Touch ID & Passcode > Change Passcode_, enter a current passcode and then enter a new passcode which is the same as current - you will see a message: "_**Enter a different passcode. Cannot re-use the same passcode.**_"

Could you please add such ability?

**Comment by rolandleth** [comment]
I will look into it, thanks!

**Comment by rolandleth** [comment]
Implemented in `3.8.3`, `c3c3cfe`. Leaving the issue open, because translations are missing.
