### ISSUE TITLE
iCloud Keychain sync

### ISSUE THREAD

**Issue by blwinters** [rolandleth/LTHPasscodeViewController#173]
It seems that the passcode stored in the keychain isn't synced between devices with iCloud Keychain. I don't see any references to this in the code or other issues, so how are passcodes stored separately? I'm glad to have this behavior, just wondering about the logic.

**Comment by rolandleth** [comment]
I never worked with iCloud Keychain, so I couldn't tell you more. All I know is that the passcode is saved in the keychain, but no idea why it's not synced - maybe because it's not an actual login?

**Comment by rolandleth** [comment]
@blwinters Can I close this issue?

**Comment by blwinters** [comment]
Closed.
