### ISSUE TITLE
Passcode screen is not appeared if user changes system time

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#174]
1. Open demo application
2. Set Passcode
3. Press Home button
4. Open Settings >> General >>Date & Time
5. Turn off Set Automatically switch
6. Change time to 1 minute back
7. Open Demo application again

There is no "Enter passcode screen". So somebody can restore your application from background without entering Passcode.

**Comment by rolandleth** [comment]
Should be an easy fix, thank you!

**Comment by rolandleth** [comment]
Fixed in [`3.8.5`](https://github.com/rolandleth/LTHPasscodeViewController/tree/3.8.5).
