### ISSUE TITLE
After deleting and installing app it's still asking passcode

### ISSUE THREAD

**Issue by t3chno** [rolandleth/LTHPasscodeViewController#177]
This can be optional.

thanks for all.

**Comment by rolandleth** [comment]
That's due to how Keychain works: the data it stores, persists across app deletion, and there's no way to detect when an app is deleted, to clear the Keychain.

**Comment by t3chno** [comment]
How, this function is not working, how can I clear keychain?

[LTHPasscodeViewController useKeychain:NO];

**Comment by rolandleth** [comment]
If you'd like, you can call `[LTHPasscodeViewController useKeychain:NO];`, yes, but then you will have to manage the saving, storing and retrieving the passcode by yourself.

**Comment by t3chno** [comment]
Perfect, thanks for information.

it these delegate functions are enough?

- (void) savePasscode:(NSString *)passcode {
    // store passcode
}

- (NSString *) passcode {
    return stored_passcode
}

-(void)deletePasscode {
    // delete stord passcode and touchId 
}

-(void)saveAllowUnlockWithTouchID:(BOOL)allowUnlockWithTouchID {
    //store somewhere this boolean
}

**Comment by rolandleth** [comment]
I would suggest you use all methods that have a non-keychain version, and you should be good to go.

**Comment by t3chno** [comment]
I don't use timer so I guess I don't need but I will double check.

Also I forgot this function. Adding here just for others.

-(BOOL)allowUnlockWithTouchID {
  return stored_touch_id_status
}

**Comment by dobiho5** [comment]
How about delete keychain when app launch with user default first run?

**Comment by dobiho5** [comment]
I solved this issue like this. 

I delete passcode in keychain when first run after install. 

if user defaults's some value (for example, "first run") is not found
[LTHPasscodeViewController deletePasscode];

and then save first run. 

I don't need to save passcode to user default .
