### ISSUE TITLE
Action bar disappears when restore application from background

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#178]
1. Open demo application
2. Set passcode
3. Press 'Change' - you see Navigation bar with 'Change passcode' title and navigation buttons
4. Press Home button and restore application to foreground

Navigation bar disappears.

**Comment by DimaSlk** [comment]
Hello, Roland!

Did you have time to look at this issue?

**Comment by rolandleth** [comment]
Hey,


Sadly, I did not, and I'm not sure if I'll have to in the upcoming week, I have a lot of work to take care of. But if you're willing to look into it and open a pull request, I'd be more than happy to look over it and accept it!

**Comment by rolandleth** [comment]
Hey,

Now I understand the "problem". It is working as intended, because when you come back, it's not the navigation bar that disappears – the change was cancelled, and what you see is the normal lockscreen.
