### ISSUE TITLE
Integration of Face-Id

### ISSUE THREAD

**Issue by krunalbhavsar** [rolandleth/LTHPasscodeViewController#184]
With launch of iPhone-X, apple introduces/replaces touch-id by face-id.

Do we have the support of same feature in this framework.

Ref Link: https://developer.apple.com/documentation/localauthentication/labiometrytype

**Comment by rolandleth** [comment]
Hello,

I will have a look this week over the documentation. Not sure I'll also implement it, too, though.

Thanks for the suggestion!

**Comment by krunalbhavsar** [comment]
This, very nice lib, will become useless without face-id as it's an alternate to Touch-Id for iPhone-X, and not much hard.

Pl. consider this update as necessary and spare your valuable time for this also

Thanks...

**Comment by rolandleth** [comment]
In no way is this intended as being offensive, but if it's _not much hard_, you can always look into it yourself, open a Pull Request, and I will merge it after everything is okay.

**Comment by rolandleth** [comment]
Face ID will work out of the box, but I will have to update the library for new translations that should contain "Face ID" instead of always "Touch ID".

**Comment by krunalbhavsar** [comment]
Thank you very much for considering my request. It would be a pleasure, if I could contribute. But I'm not much proficient in Objective-C (Working on Swift since it introduced as an iOS programming lang.).

**Comment by rolandleth** [comment]
`3.9.0` released with the required changes.
