### ISSUE TITLE
Keyboard doesn't go away

### ISSUE THREAD

**Issue by NikhilManapure** [rolandleth/LTHPasscodeViewController#186]
I have edited your delegate method's `maxNumberofFailedAttemptsReached` signature to send the controller itself to delegate. Then I present a login controller from that method. It works fine but keyboard of passcode view doesn't go and so textfield in my login controller don't work.

**Comment by rolandleth** [comment]
Have you also adjusted lines `1405` and `1406` to work with the new signature?

The demo app works properly with the current signature.

**Comment by NikhilManapure** [comment]
Signature is not a problem, and I have surely edited those two lines. The problem is that even after presenting new viewController, the keyboard from the passcode textfield don't go away.

**Comment by rolandleth** [comment]
Can you create a branch from the deme app and reproduce the bug there, please?

**Comment by NikhilManapure** [comment]
Sure, will coment here once I push the code.

**Comment by rolandleth** [comment]
Hey @NikhilManapure, any updates on this? I'd love to help, but it's been a month and a half, and I'd like to close the issue, if there's nothing I can help with.
