### ISSUE TITLE
The first char can't see in the view

### ISSUE THREAD

**Issue by timeflying** [rolandleth/LTHPasscodeViewController#190]
Hi

If I use your code , the first char and part of second char was covered by something. If I type the 'abc' then I can't see the first char 'a' and the OK button also disappeared as following :
![simulator screen shot - ipad air 2 - 2018-03-05 at 17 06 23](https://user-images.githubusercontent.com/6119146/36966805-e3641b36-2098-11e8-8f3b-65e3825120cf.png)

**Comment by timeflying** [comment]
- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];
    _animatingView.frame = self.view.bounds;
    
    [self.view setNeedsUpdateConstraints]; // I add this line , the problem was solved
}

**Comment by timeflying** [comment]
I just use your code without any modify. And the problem just happenned. And I check the code add the above  lines. The problem was gone. Thank you!

**Comment by rolandleth** [comment]
I would like to investigate, though, can you please tell me the iOS version and device it happened on?

**Comment by timeflying** [comment]
I test iOS version is 11.2.
If I use your demo project. The problem not exists.
