### ISSUE TITLE
Biometrics got disabled

### ISSUE THREAD

**Issue by davidah3** [rolandleth/LTHPasscodeViewController#195]
- (void)_applicationWillEnterForeground {
    if ([self _doesPasscodeExist] &&
        [self _didPasscodeTimerEnd]) {
        _useFallbackPasscode = NO;

**Comment by rolandleth** [comment]
Hey, thanks for opening the issue!

Could you provide more info, please?

**Comment by rolandleth** [comment]
Closing this due to lack of more information.
