### ISSUE TITLE
_failedAttempts can't reset

### ISSUE THREAD

**Issue by RexNotAloof** [rolandleth/LTHPasscodeViewController#199]
i change the password use the method 'showForChangingPasscodeInViewController',
after i reach the maxNumberOfAllowedFailedAttempts,
i call the method '[LTHPasscodeViewController close]' to close the window.
but the problem is the failedAttemptLabel is still displayed if i reopen.

i add  _failedAttempts = 0;  in the method '_cancelAndDismissMe ' and it worded.

**Comment by rolandleth** [comment]
The behavior is as intended: it keeps track of the number of failed attempts until the passcode is entered correctly.

**Comment by RexNotAloof** [comment]
how can i reset it?
if i reach the maxNumberOfAllowedFailedAttempts,maybe 1hour later i hope i can try again.

**Comment by rolandleth** [comment]
That is up to you to decide what happens when the maximum number of failed attempts is reached. You can set up a timer which resets it when it ends, I guess.

It also resets on next app launch.
