### ISSUE TITLE
iOS 13 support

### ISSUE THREAD

**Issue by ddaddy** [rolandleth/LTHPasscodeViewController#202]
I've sent a pull request to fix all but 2 of the iOS 13 deprecations (For anyone building against iOS 13 minimum).
There's just 2 that i'll have to leave up to you to take a look at.
`UIApplicationDidChangeStatusBarOrientationNotification` & `UIApplicationDidChangeStatusBarFrameNotification` notifications are deprecated and we need to use the `viewWillTransitionToSize:withTransitionCoordinator:` method instead.

**Comment by rolandleth** [comment]
I made some changes and it looks like `viewWillTransitionToSize:withTransitionCoordinator:` or notifications are not needed anymore. Would you have time to check out the latest `master` and see if everything works as you'd expect, please?

**Comment by ddaddy** [comment]
Everything seems to work as it should. Thanks

**Comment by rolandleth** [comment]
Awesome, thank you!
