### ISSUE TITLE
No method to tell whether the Passcode view is being displayed

### ISSUE THREAD

**Issue by rsoffer** [rolandleth/LTHPasscodeViewController#203]
We want to be able to know if the passcode controller is being displayed to mitigate some of the existing keyboard issues when other modals are being displayed.

For example, don't display this alert view if the passcode view is on the screen.

The closest thing I see is "didPasscodeTimerEnd" but this doesn't seem to handle the scenario of explicitly showing the lock screen regardless of timer state.

This is a great library but it seems the majority of issues and headaches boil down to the use of text fields and the keyboards. It would be much simpler if we avoided using textfields and iOS keyboards altogether and just drew a custom numpad on the screen.

**Comment by rolandleth** [comment]
I'm not really sure I understand the need.

On one hand, if you try to present it while it's on screen, it won't do anything.

On the other hand, you can check if the `view` has a `superview`.

Lastly, I guess `_isCurrentlyOnScreen` could be made public, if you _really_ need it that way.

**Comment by rsoffer** [comment]
I did explain the need, you don't want to display other screens or alerts while the passcode screen is up because they mess with the keyboard.

**Comment by rolandleth** [comment]
Sorry, you did mention that 🤦🏻‍♂️

I will release a version with a public `isCurrentlyOnScreen`, but in the mean time you can make use of `[LTHPasscodeViewController sharedUser].view.superview == nil`.

**Comment by rolandleth** [comment]
`4.0.1` released.
