### ISSUE TITLE
ios6 : LTHPasscodeView did not show keyboard.

### ISSUE THREAD

**Issue by sandy-srma** [rolandleth/LTHPasscodeViewController#69]
![screen shot 2014-07-14 at 12 44 55 pm](https://cloud.githubusercontent.com/assets/7392650/3567995/a2e8ecc4-0b27-11e4-8809-3d4101ea47f8.png)
Hi team,
Would you please help by telling that , why key board is not appearing on ios6 passcode screen.
scree attached screenshot.

**Comment by chenyi1976** [comment]
Meet same issue(keyboard not show up) in simulator(iOS 7.0 and 8.0).

But it is working in my iPhone 5 (iOS 8.3). 

For your information.

**Comment by lijie250** [comment]
sometime the keyboard not show

**Comment by rolandleth** [comment]
Please try it on the device.

**Comment by lijie250** [comment]
If you launch the addViewController in the Rootcontroller, and run in the viewdidload
    AddViewController* add = [[AddViewController alloc] init];
    UINavigationController* nav = [[UINavigationController alloc] initWithRootViewController:add];
    UIImage* image = [ColorUtils imageWithColor:[UIColor colorWithRed:.91 green:.91 blue:.91 alpha:1.0]];
    [nav.navigationBar setBackgroundImage:image forBarMetrics:UIBarMetricsDefault];
    //[self setModalPresentationStyle:UIModalPresentationCurrentContext];
    [self.navigationController presentViewController:nav animated:YES completion:nil];
