### ISSUE TITLE
Showing Lock screen with a non-simple password

### ISSUE THREAD

**Issue by iltercengiz** [rolandleth/LTHPasscodeViewController#73]
To show the full keyboard we call this: 

`- (void)setIsSimple:(BOOL)isSimple inViewController:(UIViewController *)viewController asModal:(BOOL)isModal`

But it requires `viewController` to be non-nil.
So how can I show it when app is coming from background, as I call 

`- (void)showLockScreenWithAnimation:(BOOL)animated withLogout:(BOOL)hasLogout andLogoutTitle:(NSString*)logoutTitle`

from the AppDelegate?

**Comment by rolandleth** [comment]
Hey, this is really old now, and #134 has some improvements for `isSimple`. Can you look at it and see if it solves your issue?

**Comment by iltercengiz** [comment]
I don't have the code base currently but looking at the changes, it seems like a solution.

**Comment by rolandleth** [comment]
Awesome, thanks!
