### ISSUE TITLE
Not compiling in App Extension (iOS 8)

### ISSUE THREAD

**Issue by sylverb** [rolandleth/LTHPasscodeViewController#88]
Hello,
When compiling in an App extension (in my case a Document Provider), I have several errors due to the fact that "[UIApplication sharedApplication]" (which is used in your case to get the interface orientation) is not available in App extensions :
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by rolandleth** [comment]
I suppose I can close this? Still not working, but the PR had to be rebased and I got no more answers there, so I'm trying my final luck here before closing it.
